name: Lint and Format

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Prettier check
        run: npm run format:check
      - name: ESLint
        run: npm run lint
      - name: Check menu translations
        run: npm run check:menu-translations
